// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLX2BVfSCEqZvt-0-TuJYHSnH0za0ba6s',
    appId: '1:259988227090:web:65fe7669283953436c04cb',
    messagingSenderId: '259988227090',
    projectId: 'project-rider-1b5ac',
    authDomain: 'project-rider-1b5ac.firebaseapp.com',
    databaseURL: 'https://project-rider-1b5ac-default-rtdb.firebaseio.com',
    storageBucket: 'project-rider-1b5ac.appspot.com',
    measurementId: 'G-8Y1CHR7DH5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiVnY-8Ajak4xVeQNLzynr8skqCgNFulg',
    appId: '1:259988227090:android:3b5b3411977fbae16c04cb',
    messagingSenderId: '259988227090',
    projectId: 'project-rider-1b5ac',
    databaseURL: 'https://project-rider-1b5ac-default-rtdb.firebaseio.com',
    storageBucket: 'project-rider-1b5ac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9lRm9qBJhfz4KbeOMlX6dIy-_hUBgfno',
    appId: '1:259988227090:ios:f33be07ff4b84f8f6c04cb',
    messagingSenderId: '259988227090',
    projectId: 'project-rider-1b5ac',
    databaseURL: 'https://project-rider-1b5ac-default-rtdb.firebaseio.com',
    storageBucket: 'project-rider-1b5ac.appspot.com',
    iosBundleId: 'com.example.projectConcertCloseiin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9lRm9qBJhfz4KbeOMlX6dIy-_hUBgfno',
    appId: '1:259988227090:ios:f33be07ff4b84f8f6c04cb',
    messagingSenderId: '259988227090',
    projectId: 'project-rider-1b5ac',
    databaseURL: 'https://project-rider-1b5ac-default-rtdb.firebaseio.com',
    storageBucket: 'project-rider-1b5ac.appspot.com',
    iosBundleId: 'com.example.projectConcertCloseiin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLX2BVfSCEqZvt-0-TuJYHSnH0za0ba6s',
    appId: '1:259988227090:web:ff6305ccf635975c6c04cb',
    messagingSenderId: '259988227090',
    projectId: 'project-rider-1b5ac',
    authDomain: 'project-rider-1b5ac.firebaseapp.com',
    databaseURL: 'https://project-rider-1b5ac-default-rtdb.firebaseio.com',
    storageBucket: 'project-rider-1b5ac.appspot.com',
    measurementId: 'G-RSP43PD86P',
  );
}
